### ISSUE TITLE
Specification of REST interface

### ISSUE THREAD

**Issue by NorDar** [sopra-fs24-group-01/sopra-fs24-plantparent-project-management#6]
For the communication between the client and the server, a REST interface will be used. You have to create a specification for this REST interface. In particular, describe the entities with their operations, parameters, parameter types, returned values, and HTTP status codes. For an example of a REST specification, please refer to assignment sheet 1. With a precise specification, developers of the client and server should be able to work independently on their tasks.

**Advice**: Use the methods (HTTP verbs) as they were intended to. Use HTTP status codes to indicate correct or incorrect requests. Optionally, design your interface in a way such that it follows the HATEOAS principle as described in this guide.

* https://restfulapi.net/hateoas/
* https://spring.io/guides/gs/rest-hateoas/

To Be refined (Subtasks according to entities and their operations. etc.):
- [x] users
- [x] plants
- [x] collaboration logic -> link users and plants
- [ ] schedules
- [ ] schedule events
- [x] spaces
- [ ] ... More?

**Comment by lazi-nhr** [comment]
Done. 
See M2 Report: https://docs.google.com/document/d/1iIYlj3k_1UTVW4w5OFjdffgsm1VBjwET8kLfO_Ww_ZY/edit#heading=h.58vmtxy30y58
